language: generic
sudo: required
services:
    - docker 

before_install:
    - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true react-test npm test

after_success:
    - docker build -t sommysab/multi-client ./client
    - docker build -t sommysab/multi-nginx ./nginx
    - docker build -t sommysab/multi-server ./server
    - docker build -t sommysab/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    - docker push sommysab/multi-client
    - docker push sommysab/multi-nginx
    - docker push sommysab/multi-server
    - docker push sommysab/multi-worker
    